# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menubar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(735, 441)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(Form)
        self.icon_only_widget.setMaximumSize(QtCore.QSize(62, 16777215))
        self.icon_only_widget.setAutoFillBackground(False)
        self.icon_only_widget.setStyleSheet("QWidget{\n"
"    background-color: rgb(31, 149, 239);\n"
"\n"
"}\n"
"QPushButton{\n"
"      color:white;\n"
"height:30px;\n"
"border:none;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QPushButton:checked{\n"
"background-color:#F5FAFE;\n"
"color:#1F95EF;\n"
"font-weight:bold;\n"
"}")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.icon_only_widget)
        self.label_7.setMinimumSize(QtCore.QSize(40, 40))
        self.label_7.setMaximumSize(QtCore.QSize(40, 40))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("D:\MyFiles\Sidebar\slidemenubar/profile_pic.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_8.setSpacing(15)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Dashboard_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.Dashboard_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\MyFiles\Sidebar\slidemenubar/dashboard_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("D:\MyFiles\Sidebar\slidemenubar/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Dashboard_1.setIcon(icon)
        self.Dashboard_1.setCheckable(True)
        self.Dashboard_1.setAutoExclusive(True)
        self.Dashboard_1.setObjectName("Dashboard_1")
        self.verticalLayout_8.addWidget(self.Dashboard_1)
        self.Profile_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.Profile_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\MyFiles\Sidebar\slidemenubar/profile_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("D:\MyFiles\Sidebar\slidemenubar/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Profile_1.setIcon(icon1)
        self.Profile_1.setCheckable(True)
        self.Profile_1.setAutoExclusive(True)
        self.Profile_1.setObjectName("Profile_1")
        self.verticalLayout_8.addWidget(self.Profile_1)
        self.Messages_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.Messages_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\MyFiles\Sidebar\slidemenubar/messages_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("D:\MyFiles\Sidebar\slidemenubar/messages.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Messages_1.setIcon(icon2)
        self.Messages_1.setCheckable(True)
        self.Messages_1.setAutoExclusive(True)
        self.Messages_1.setObjectName("Messages_1")
        self.verticalLayout_8.addWidget(self.Messages_1)
        self.Notifications_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.Notifications_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\MyFiles\Sidebar\slidemenubar/notifications_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("D:\MyFiles\Sidebar\slidemenubar/notifications.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Notifications_1.setIcon(icon3)
        self.Notifications_1.setCheckable(True)
        self.Notifications_1.setAutoExclusive(True)
        self.Notifications_1.setObjectName("Notifications_1")
        self.verticalLayout_8.addWidget(self.Notifications_1)
        self.Setting_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.Setting_1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\MyFiles\Sidebar\slidemenubar/settings_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("D:\MyFiles\Sidebar\slidemenubar/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Setting_1.setIcon(icon4)
        self.Setting_1.setCheckable(True)
        self.Setting_1.setAutoExclusive(True)
        self.Setting_1.setObjectName("Setting_1")
        self.verticalLayout_8.addWidget(self.Setting_1)
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        spacerItem = QtWidgets.QSpacerItem(20, 136, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.pushButton_30 = QtWidgets.QPushButton(self.icon_only_widget)
        self.pushButton_30.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("D:\MyFiles\Sidebar\slidemenubar/log_out_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_30.setIcon(icon5)
        self.pushButton_30.setCheckable(True)
        self.pushButton_30.setObjectName("pushButton_30")
        self.verticalLayout_7.addWidget(self.pushButton_30)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.icon_name_widget = QtWidgets.QWidget(Form)
        self.icon_name_widget.setMaximumSize(QtCore.QSize(145, 16777215))
        self.icon_name_widget.setAutoFillBackground(False)
        self.icon_name_widget.setStyleSheet("QWidget{\n"
"    background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton{\n"
"      color:white;\n"
"text-align:left;\n"
"height:30px;\n"
"border:none;\n"
"padding-left:10px;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:#F5FAFE;\n"
"color:#1F95EF;\n"
"font-weight:bold;\n"
"}")
        self.icon_name_widget.setObjectName("icon_name_widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.icon_name_widget)
        self.verticalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.icon_name_widget)
        self.label_5.setMinimumSize(QtCore.QSize(40, 40))
        self.label_5.setMaximumSize(QtCore.QSize(40, 40))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\MyFiles\Sidebar\slidemenubar/profile_pic.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.icon_name_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_6.setSpacing(15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Dashboard_2 = QtWidgets.QPushButton(self.icon_name_widget)
        self.Dashboard_2.setIcon(icon)
        self.Dashboard_2.setCheckable(True)
        self.Dashboard_2.setAutoExclusive(True)
        self.Dashboard_2.setObjectName("Dashboard_2")
        self.verticalLayout_6.addWidget(self.Dashboard_2)
        self.Profile_2 = QtWidgets.QPushButton(self.icon_name_widget)
        self.Profile_2.setIcon(icon1)
        self.Profile_2.setCheckable(True)
        self.Profile_2.setAutoExclusive(True)
        self.Profile_2.setObjectName("Profile_2")
        self.verticalLayout_6.addWidget(self.Profile_2)
        self.Messages_2 = QtWidgets.QPushButton(self.icon_name_widget)
        self.Messages_2.setIcon(icon2)
        self.Messages_2.setCheckable(True)
        self.Messages_2.setAutoExclusive(True)
        self.Messages_2.setObjectName("Messages_2")
        self.verticalLayout_6.addWidget(self.Messages_2)
        self.Notifications_2 = QtWidgets.QPushButton(self.icon_name_widget)
        self.Notifications_2.setIcon(icon3)
        self.Notifications_2.setCheckable(True)
        self.Notifications_2.setAutoExclusive(True)
        self.Notifications_2.setObjectName("Notifications_2")
        self.verticalLayout_6.addWidget(self.Notifications_2)
        self.Setting_2 = QtWidgets.QPushButton(self.icon_name_widget)
        self.Setting_2.setIcon(icon4)
        self.Setting_2.setCheckable(True)
        self.Setting_2.setAutoExclusive(True)
        self.Setting_2.setObjectName("Setting_2")
        self.verticalLayout_6.addWidget(self.Setting_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 136, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.pushButton_24 = QtWidgets.QPushButton(self.icon_name_widget)
        self.pushButton_24.setIcon(icon5)
        self.pushButton_24.setCheckable(True)
        self.pushButton_24.setObjectName("pushButton_24")
        self.verticalLayout_5.addWidget(self.pushButton_24)
        self.gridLayout.addWidget(self.icon_name_widget, 0, 1, 1, 1)
        self.mainmenu = QtWidgets.QWidget(Form)
        self.mainmenu.setAutoFillBackground(False)
        self.mainmenu.setStyleSheet("background-color: rgb(245, 250, 254);")
        self.mainmenu.setObjectName("mainmenu")
        self.widget_3 = QtWidgets.QWidget(self.mainmenu)
        self.widget_3.setGeometry(QtCore.QRect(10, 0, 461, 61))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Menu = QtWidgets.QPushButton(self.widget_3)
        self.Menu.setStyleSheet("border:none;")
        self.Menu.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("D:\MyFiles\Sidebar\slidemenubar/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Menu.setIcon(icon6)
        self.Menu.setIconSize(QtCore.QSize(20, 20))
        self.Menu.setCheckable(True)
        self.Menu.setObjectName("Menu")
        self.horizontalLayout_9.addWidget(self.Menu)
        spacerItem2 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_10.addWidget(self.lineEdit_3)
        self.pushButton_32 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_32.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("D:\MyFiles\Sidebar\slidemenubar/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_32.setIcon(icon7)
        self.pushButton_32.setObjectName("pushButton_32")
        self.horizontalLayout_10.addWidget(self.pushButton_32)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        spacerItem3 = QtWidgets.QSpacerItem(97, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.pushButton_33 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_33.setStyleSheet("border:none;\n"
"")
        self.pushButton_33.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("D:\MyFiles\Sidebar\slidemenubar/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_33.setIcon(icon8)
        self.pushButton_33.setObjectName("pushButton_33")
        self.horizontalLayout_9.addWidget(self.pushButton_33)
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.mainmenu)
        self.stackedWidget_3.setGeometry(QtCore.QRect(10, 80, 461, 381))
        self.stackedWidget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.dashboardpage = QtWidgets.QWidget()
        self.dashboardpage.setObjectName("dashboardpage")
        self.label = QtWidgets.QLabel(self.dashboardpage)
        self.label.setGeometry(QtCore.QRect(140, 150, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.stackedWidget_3.addWidget(self.dashboardpage)
        self.meassagespage = QtWidgets.QWidget()
        self.meassagespage.setObjectName("meassagespage")
        self.label_8 = QtWidgets.QLabel(self.meassagespage)
        self.label_8.setGeometry(QtCore.QRect(140, 150, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.stackedWidget_3.addWidget(self.meassagespage)
        self.notificationspage = QtWidgets.QWidget()
        self.notificationspage.setObjectName("notificationspage")
        self.label_9 = QtWidgets.QLabel(self.notificationspage)
        self.label_9.setGeometry(QtCore.QRect(120, 140, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.stackedWidget_3.addWidget(self.notificationspage)
        self.settingpage = QtWidgets.QWidget()
        self.settingpage.setObjectName("settingpage")
        self.label_11 = QtWidgets.QLabel(self.settingpage)
        self.label_11.setGeometry(QtCore.QRect(140, 130, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.stackedWidget_3.addWidget(self.settingpage)
        self.profilepage = QtWidgets.QWidget()
        self.profilepage.setObjectName("profilepage")
        self.label_10 = QtWidgets.QLabel(self.profilepage)
        self.label_10.setGeometry(QtCore.QRect(150, 150, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.stackedWidget_3.addWidget(self.profilepage)
        self.gridLayout.addWidget(self.mainmenu, 0, 2, 1, 1)

        self.retranslateUi(Form)
        self.Menu.toggled['bool'].connect(self.icon_only_widget.setHidden) # type: ignore
        self.Menu.toggled['bool'].connect(self.icon_name_widget.setVisible) # type: ignore
        self.Setting_1.toggled['bool'].connect(self.Setting_2.setChecked) # type: ignore
        self.Notifications_1.toggled['bool'].connect(self.Notifications_2.setChecked) # type: ignore
        self.Messages_1.toggled['bool'].connect(self.Messages_2.setChecked) # type: ignore
        self.Profile_1.toggled['bool'].connect(self.Profile_2.setChecked) # type: ignore
        self.Dashboard_1.toggled['bool'].connect(self.Dashboard_2.setChecked) # type: ignore
        self.Dashboard_2.toggled['bool'].connect(self.Dashboard_1.setChecked) # type: ignore
        self.Profile_2.toggled['bool'].connect(self.Profile_1.setChecked) # type: ignore
        self.Messages_2.toggled['bool'].connect(self.Messages_1.setChecked) # type: ignore
        self.Notifications_2.toggled['bool'].connect(self.Notifications_1.setChecked) # type: ignore
        self.Setting_2.toggled['bool'].connect(self.Setting_1.setChecked) # type: ignore
        self.pushButton_24.toggled['bool'].connect(Form.close) # type: ignore
        self.pushButton_30.toggled['bool'].connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Sidebar"))
        self.Dashboard_2.setText(_translate("Form", "Dashboard"))
        self.Profile_2.setText(_translate("Form", "Profile"))
        self.Messages_2.setText(_translate("Form", "Messages"))
        self.Notifications_2.setText(_translate("Form", "Notifications"))
        self.Setting_2.setText(_translate("Form", "Settings"))
        self.pushButton_24.setText(_translate("Form", "Signout"))
        self.label.setText(_translate("Form", "Dashboard Page"))
        self.label_8.setText(_translate("Form", "Messages Page"))
        self.label_9.setText(_translate("Form", "Notifications Page"))
        self.label_11.setText(_translate("Form", "Settings Page"))
        self.label_10.setText(_translate("Form", "Profile Page"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
